name: Birthday Reminder Bot

on:
  schedule:
    # Запуск щодня о 06:00 за UTC (це 09:00 за київським часом)
    - cron: '30 13 * * *'
  # Дозволяє запустити скрипт вручну з сайту GitHub (для тестів)
  workflow_dispatch:

jobs:
  check-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Завантаження коду
        uses: actions/checkout@v4

      - name: Встановлення Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Встановлення залежностей
        run: npm install

      - name: Компіляція TypeScript
        run: npm run build

      - name: Запуск бота
        run: npm start
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}